### ISSUE TITLE
Form components where the mapping for an upstream table's name is the same as one of its primary keys cannot be inserted into.

### ISSUE THREAD

**Issue by A-Baji** [datajoint/sci-viz#59]
This occurs due to the [logic of foreign key mapping to the insert payload](https://github.com/datajoint/sci-viz/blob/8471bb82cde9b856713d0e57801b587a8fd5b454/src/Components/Form/DynamicForm.tsx#L173)

### Tables
```
@group1_simple
class TableA(dj.Lookup):
    definition = """
    a_id: int
    ---
    a_name: varchar(30)
    """
@group1_simple
class TableB(dj.Lookup):
    definition = """
    -> TableA
    b_id: int
    ---
    b_number: float
    """
```
### Spec sheet
```
Bugged form:
   route: /insert
   x: 0
   y: 2
   height: 1
   width: 1
   type: form
   tables:
      - test_group1_simple.TableB
   map:
      - type: table
      input: a_id
      destination: test_group1_simple.TableA
```
### Error
```
Insert failed!
translate_query_error(err, query) datajoint.errors.MissingAttributeError: Field 'a_id' doesn't have a default value
```
